# Generated by Django 5.0.6 on 2024-07-01 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0003_ruta_remove_productos_categorias_boleto_viaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='boleto',
            name='numero_asiento',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AddField(
            model_name='boleto',
            name='reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VentasApp.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
