# Generated by Django 5.0.6 on 2024-07-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0004_remove_boleto_cliente_remove_boleto_fecha_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='viaje',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='numero_asiento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_doble_piso', models.BooleanField(default=False)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('idAsiento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_asiento', models.CharField(max_length=10)),
                ('piso', models.CharField(blank=True, max_length=1, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.carro')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VentasApp.carro'),
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
