# Generated by Django 5.0.6 on 2024-07-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0005_remove_reserva_viaje_alter_boleto_numero_asiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='capacidad_maxima',
        ),
    ]
