# Generated by Django 5.0.6 on 2024-07-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0006_remove_carro_capacidad_maxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='numero_asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasApp.asiento'),
        ),
    ]
